### ISSUE TITLE
English language.toml

### ISSUE THREAD

**Issue by TheDiscordian** [Euphillya/Skyllia#32]
I did a ChatGPT translation of language.toml, it turned out quite well:

```toml
config-version = 1
verbose = false

[island]
	[island.trust]
		sucess = "The player has been added to your trust list until the next restart or until you remove them directly. Note that a trusted person has the same permissions as a member of your island."
		not-enough-args = "The command is incomplete: /skyllia trust <player>"
	[island.access]
		close = "Your island is now closed."
		open = "Your island is now open."
	[island.expel]
		not-enough-args = "The command is incomplete: /skyllia expel <player>"
		player-not-in-island = "The player is not on your island."
		player-failed = "The player cannot be expelled from your island."
	[island.permission]
		fail-high-equals-status = "You cannot modify your own permissions or the permissions of roles higher than yours."
	[island.delete]
		success = "The island has been successfully deleted."
		only-owner = "Sorry, only the owner can execute this command."
	[island.ban]
		failed-player-in-island = "The player cannot be banned as they are a member of your island."
		success = "The player has been banned from your island."
		not-enough-args = "The command is incomplete: /skyllia ban <player>"
	[island.generic]
		not-member = "The player is not a member of the island."
		error = "An error occurred. Please contact an administrator."
		only-owner = "Only the island owner can do this."

		[island.generic.location]
			not-safe = "The location is not safe! Teleportation not possible."
		[island.generic.player]
			not-found = "The player is not found."
			offline = "The player is offline."
			no-island = "You do not have an island!"
			permission-denied = "You do not have permission to do this."
			already-exist = "You already have an island."
			command-already-execution = "The command is already being executed, please wait a moment."
			not-in-island = "You must be on your island."
	[island.home]
		success = "You have been teleported to your island."

		[island.home.set]
			success = "You have updated your home!"
	[island.promote]
		fail = "Player %s cannot be promoted."
		fail-high-equals-status = "You cannot promote a player to your rank or higher."
		success = "Player %s has been promoted."
		not-enough-args = "The command is incomplete: /skyllia promote <member>"
	[island.unban]
		success = "The player has been unbanned."
		player-not-banned = "The player is not banned."
		not-enough-args = "The command is incomplete: /skyllia unban <player>"
		failed = "The player was not banned for an unknown reason."
	[island.demote]
		fail = "Player %s cannot be demoted."
		fail-high-equals-status = "You cannot demote a player of your rank or higher."
		success = "Player %s has been demoted."
		not-enough-args = "The command is incomplete: /skyllia demote <member>"
	[island.gamerule]
		success = "The gamerule has been updated."
		not-enough-args = "The command is incomplete: /skyllia gamerule <GAMERULE> <true/false>"
		failed = "An error occurred while updating the gamerule."
		gamerule-invalid = "The gamerule does not exist."
	[island.kick]
		fail-high-equals-status = "You cannot kick a player of your rank or higher."
		success = "You are now a member of the island!"
		failed = "The player could not be kicked. If the problem persists, contact an administrator."
		not-enough-args = "The command is incomplete: /skyllia kick <player>"
	[island.biome]
		change-in-progress = "Biome change in progress. Please note that it takes time... A message will alert you when the process is complete."
		success = "Biome change in the chunk where you were is complete!"
		only-island = "The command can only be executed on an island."
		not-enough-args = "The command is incomplete: /skyllia biome <biome>"
		biome-not-exist = "The biome %s does not exist."
	[island.leave]
		success = "You have left your island."
		failed = "You could not leave your island. If the problem persists, contact an administrator."
		he-is-owner = "You cannot leave your island because you are the owner!"
	[island.permissions]
		permissions-invalid = "This permission does not exist."
		role-invalid = "The role is invalid, possibilities: <OWNER/CO_OWNER/MODERATOR/MEMBER/VISITOR/BAN>"
		not-enough-args = "The command is incomplete: /skyllia permission <island/commands/inventory> <OWNER/CO_OWNER/MODERATOR/MEMBER/VISITOR/BAN> <PERMISSION_NAME> <true/false>"
		permission-type-invalid = "The type is invalid, possibilities: <island/commands/inventory>"

		[island.permissions.update]
			success = "Permission has been updated!"
			failed = "The change could not be made."
	[island.transfert]
		success = "The new owner of the island is: %new_owner%"
	[island.create]
		type-no-exist = "The selected island type does not exist."
		finish = "Welcome to your island!"
		error = "An error occurred while creating the island."
		in-progress = "The island is being created"
		schem-no-exist = "The schematic to create the island does not exist."
	[island.untrust]
		success = "The member is no longer part of your trusts."
		not-enough-args = "The command is incomplete: /skyllia untrust <player>"
		failed = "The command is incomplete: /skyllia untrust <player>"
	[island.invite]
		already-on-an-island = "You are already on an island!"
		not-enough-args = "The command is incomplete: /skyllia invite <add/accept/decline> <player/island_owner>"

		[island.invite.add]
			notification-player = "Player %player_invite% has invited you to their island. To accept: /skyllia invite accept %player_invite%. To decline: /skyllia invite decline %player_invite%"
			pending = "Player %s has been invited successfully. Waiting for a response..."
			not-enough-args = "You must specify which island you want to decline: /skyllia invite add <player>"
		[island.invite.decline]
			owner-not-island = "The island of player %s was not found."
			not-enough-args = "You must specify which island you want to decline: /skyllia invite decline <island_owner>"
		[island.invite.accept]
			owner-not-island = "The island of player %s was not found."
			success = "You are now a member of the island!"
			max-member-exceeded = "The maximum member limit of the island has been reached. You cannot join the island."
			not-enough-args = "You must specify which island you want to join: /skyllia invite accept <island_owner>"
	[island.visit]
		island-not-open = "The island is closed."
		success = "You have been teleported to %player%'s island."
		player-not-island = "The player does not have an island."
		not-enough-args = "You must specify the name of the island you want to visit: /skyllia visit <player>"
		player-banned = "You are banned from the island."
	[island.warp]
		success = "Your warp: %s has been created."
		not-enough-args = "You must specify the name of the warp to save: /skyllia <set/del>warp <warp_name>"

		[island.warp.teleport]
			not-exist = "The requested warp does not exist."
			success = "You have been teleported to the requested warp."
		[island.warp.delete]
			success = "The warp has been deleted."
			can-not-delete-home = "You cannot delete the home warp."
[admin]
	[admin.commands]
		[admin.commands.island]
			[admin.commands.island.setmaxmembers]
				no-confirm = "You did not add \"confirm\" at the end."
				nan = "The specified number is incorrect."
				not-enough-args = "The command is incomplete: /skyllia setmaxmembres value confirm"
			[admin.commands.island.delete]
				no-confirm = "You must add \"confirm\" at the end of your command."
				not-enough-args = "The player's name is missing."
			[admin.commands.island.setsize]
				no-confirm = "You must add the argument \"confirm\" at the end of your command."
				success = "The number of people on the island has been successfully changed."
				nan = "You did not choose an integer."
				not-enough-args = "The command is incomplete: /skylladmin setsize <player/uuid> <number> confirm"
				failed = "The change could not be made."

```

I'd be happy to PR this in, but I'm unsure how you'd like it done 😃.
